spring:
  application:
    name: scloud-admin-service

eureka:
    client:
      register-with-eureka: true
      fetch-registry: false
      service-url:
        default-zone: http://localhost:8761/eureka

server:
  port: 7777