spring:
  application:
    name: scloud-gateway-auth-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service-registration
            uri: lb://scloud-auth-service
            predicates:
              - Path=/api/users/**
            filters:
              - StripPrefix=1
          - id: auth-service-token-generation
            uri: lb://scloud-auth-service
            predicates:
              - Path=/api/auth/**
            filters:
              - StripPrefix=1
          - id: product-service
            uri: lb://scloud-product-service
            predicates:
              - Path=/api/products/**
            filters:
              - StripPrefix=1

server:
  port: 8111

security:
  jwt:
    secret-key: springsecurityjwtsecret
    token-duration: 1D



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"