spring:
  application:
    name: scloud-notification-service
  kafka:
    bootstrap-servers: localhost:9092
#    consumer:
#      properties:
#        spring.deserializer.trusted.packages: "com.labs.scloud.discovery.model,com.labs.scloud.kafka.*"
#    consumer:
#      key-deserializer: org.apache.kafka.common.deserialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.deserialization.JsonDeserializer


eureka:
    client:
      register-with-eureka: true
      fetch-registry: false
      service-url:
        default-zone: http://localhost:8761/eureka

server:
  port: 7080


