spring:
  application:
    name: config-client
  profiles:
    active:
      - default
  config:
    import:
#      - "configserver:http://localhost:8888/"
      - "optional:configserver:"

#eureka:
#    client:
#      register-with-eureka: true
#      fetch-registry: true
#      service-url:
#        default-zone: http://localhost:8761/eureka

#welcome:
#  message: "Hello from Config Client Application"

##Config File profile
#spring.cloud.config.profile=default
#
##Loading Configs from central config server
##spring.config.import=configserver:http://localhost:8888
##spring.config.import=optional:configserver:http://localhost:8888
#
##Loading configs from central config server through service discovery
#spring.config.import=optional:configserver:

server:
  port: 7077

management:
  endpoints:
    web:
      exposure:
        include: "*"

#Loads config files from File System
#spring.cloud.config.server.native.search-locations=file:///C:/temp/config/
#spring.profiles.active=native

